"""Add days_taken to medications

Revision ID: 243775af115f
Revises: 212c9da80a7b
Create Date: 2024-11-19 16:59:38.258267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243775af115f'
down_revision = '212c9da80a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_taken', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_column('days_taken')

    # ### end Alembic commands ###
