"""Added dosage and price columns to Medications

Revision ID: 262b234637db
Revises: 4cdb9e768b8c
Create Date: 2024-10-21 17:25:33.009662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262b234637db'
down_revision = '4cdb9e768b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dosage', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('price')
        batch_op.drop_column('dosage')

    # ### end Alembic commands ###
