"""Added relationship to MedicationData in Medications model

Revision ID: 41af7d46ac02
Revises: 6fdffdb9aa91
Create Date: 2024-10-22 16:15:35.536372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41af7d46ac02'
down_revision = '6fdffdb9aa91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_medications')
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.alter_column('time_of_day',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('days_of_week',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.alter_column('days_of_week',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('time_of_day',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    op.create_table('_alembic_tmp_medications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=False),
    sa.Column('duration', sa.VARCHAR(length=50), nullable=True),
    sa.Column('dosage', sa.VARCHAR(length=50), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('medication_data', sa.INTEGER(), nullable=True),
    sa.Column('time_of_day', sa.VARCHAR(length=50), server_default=sa.text("'as Needed'"), nullable=False),
    sa.Column('days_of_week', sa.VARCHAR(length=50), server_default=sa.text("'all'"), nullable=False),
    sa.ForeignKeyConstraint(['medication_data'], ['medicationData.id'], name='fk_medications_medication_data'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
