"""added time an days to medication

Revision ID: 4e1bd7f4b540
Revises: de1bffd07aab
Create Date: 2024-10-22 15:42:38.639549

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e1bd7f4b540"
down_revision = "de1bffd07aab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("medications", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "time_of_day",
                sa.String(length=50),
                nullable=False,
                server_default="as needed",
            )
        )
        batch_op.add_column(
            sa.Column(
                "days_of_week",
                sa.String(length=50),
                nullable=False,
                server_default="all",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("medications", schema=None) as batch_op:
        batch_op.drop_column("days_of_week")
        batch_op.drop_column("time_of_day")

    with op.batch_alter_table("medicationData", schema=None) as batch_op:
        batch_op.drop_column("days_of_week")
        batch_op.drop_column("time_of_day")

    # ### end Alembic commands ###
