"""update fields

Revision ID: 72df2fcbf99c
Revises: 86de430c5559
Create Date: 2024-10-22 13:11:38.289624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72df2fcbf99c'
down_revision = '86de430c5559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_medicationData')
    with op.batch_alter_table('medicationData', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('medical_condition_url',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('drug_link',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dosage', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('account_type', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('account_type')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('price')
        batch_op.drop_column('dosage')

    with op.batch_alter_table('medicationData', schema=None) as batch_op:
        batch_op.alter_column('drug_link',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('medical_condition_url',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_medicationData',
    sa.Column('drug_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('medical_condition', sa.VARCHAR(length=100), nullable=False),
    sa.Column('medical_condition_description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('activity', sa.VARCHAR(length=100), nullable=True),
    sa.Column('rx_otc', sa.VARCHAR(length=50), nullable=True),
    sa.Column('pregnancy_category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('csa', sa.VARCHAR(length=50), nullable=True),
    sa.Column('alcohol', sa.VARCHAR(length=50), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.Column('no_of_reviews', sa.INTEGER(), nullable=True),
    sa.Column('medical_condition_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('drug_link', sa.VARCHAR(length=200), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False)
    )
    # ### end Alembic commands ###
